configuration:
  version: "2.0.0"
  debug-mode: false
  metrics-enabled: true
  language: "english"
  check-time-every: 20
updater:
  channel: "db"
  remind-on-login: true
  permission-node: "minereset.admin"